### ISSUE TITLE
Unresizeable window not resizing

### ISSUE THREAD

**Issue by JuNi4** [DM8AT/GLGE#6]
when `glgeSetWindowResizable(false);` is called and the apllication is maximized, it won't resize

**Comment by DM8AT** [comment]
Switched some things in the back end of the function, it is now even more stable and just dosn't show the button for maximizing the window when window resizing is disabled. 
It is now using SDL_SetWindowResizable, instead of checking on window updates if the window resizing is allowed. This makes it feel more stable and less buggy. 
The changes are pushed shortly, in the next small patch.

**Comment by JuNi4** [comment]
SoonTM

**Comment by JuNi4** [comment]
@DM8AT SoonTM
